"""
Role Catalogue Seed Data — AccessMind Phase 3.5
------------------------------------------------
45 enterprise access roles across 10 applications.
Every role includes realistic descriptions, governance metadata,
and integration-awareness fields (source_system, external_id, sync_status).

Applications:
  Splunk, CyberArk, Azure, GitHub, Jira, ServiceNow,
  Okta, AWS, SailPoint, Cribl
"""

from datetime import date
from database import SessionLocal, engine
from models import Base
from sqlalchemy import text

Base.metadata.create_all(bind=engine)

ROLES = [
    # ── Splunk ────────────────────────────────────────────────────────────────
    {
        "role_name": "Splunk-Read-PRD",
        "application": "Splunk",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Provides read-only access to Splunk production dashboards, saved searches, and pre-built reports. Users can view security events and operational metrics but cannot create, modify, or share content. Suitable for stakeholders and business users who need visibility into security posture without operational access.",
        "owner_team": "Cyber Security",
        "approval_owner": "CISO",
        "requestable": True,
        "assigned_user_count": 34,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 11, 15),
        "source_system": "Splunk Enterprise Security",
        "source_type": "siem",
        "external_id": "splunk-role-read-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Splunk-Power-User",
        "application": "Splunk",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Grants full search capabilities across all Splunk production indexes, ability to create and share dashboards, build alerts, and write SPL queries. Users can schedule reports and create data models. Intended for SOC analysts and security engineers who actively investigate incidents and build detection content.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 12,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 10, 30),
        "source_system": "Splunk Enterprise Security",
        "source_type": "siem",
        "external_id": "splunk-role-poweruser-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Splunk-Admin-PRD",
        "application": "Splunk",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full administrative access to Splunk production environment including index management, user provisioning, forwarder configuration, and system configuration. Can install apps, manage data inputs, and modify retention policies. Restricted to Splunk platform administrators. Any change impacts all Splunk users and data pipelines.",
        "owner_team": "Cyber Security",
        "approval_owner": "CISO",
        "requestable": False,
        "assigned_user_count": 3,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 9, 1),
        "source_system": "Splunk Enterprise Security",
        "source_type": "siem",
        "external_id": "splunk-role-admin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Splunk-Power-User-UAT",
        "application": "Splunk",
        "environment": "UAT",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Grants full search and content creation capabilities in the Splunk UAT environment. Used for testing new dashboards, alert logic, and SPL queries before promotion to production. Suitable for analysts building or validating detection content in a non-production context.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 8,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "Splunk Enterprise Security",
        "source_type": "siem",
        "external_id": "splunk-role-poweruser-uat-001",
        "sync_status": "synced",
    },

    # ── CyberArk ──────────────────────────────────────────────────────────────
    {
        "role_name": "CyberArk-Vault-Operator",
        "application": "CyberArk",
        "environment": "PRD",
        "access_type": "Operator",
        "is_privileged": True,
        "description": "Provides privileged vault operator access in CyberArk PAM, including ability to retrieve, rotate, and manage credentials stored in designated safes. Operators can check out privileged accounts for session recording. This role carries significant security risk — misuse could expose production credentials across all managed systems. Requires CISO approval and quarterly review.",
        "owner_team": "Cyber Security",
        "approval_owner": "CISO",
        "requestable": False,
        "assigned_user_count": 5,
        "stale_finding_count": 3,
        "last_reviewed_date": date(2025, 8, 15),
        "source_system": "CyberArk PAM",
        "source_type": "pam",
        "external_id": "cyberark-role-vaultop-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "CyberArk-Safe-Manager",
        "application": "CyberArk",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Grants safe management capabilities in CyberArk including creating and configuring safes, managing safe members, and setting access policies. Safe managers control who can access credential groups and define retention policies. Reserved for PAM administrators and senior security engineers managing privileged access infrastructure.",
        "owner_team": "Cyber Security",
        "approval_owner": "CISO",
        "requestable": False,
        "assigned_user_count": 2,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 7, 1),
        "source_system": "CyberArk PAM",
        "source_type": "pam",
        "external_id": "cyberark-role-safemanager-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "CyberArk-ReadOnly",
        "application": "CyberArk",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Read-only access to CyberArk PAM audit logs, session recordings, and safe listings. Cannot retrieve or rotate credentials. Used by auditors and compliance teams to review privileged access activity and verify governance controls without the ability to interact with stored credentials.",
        "owner_team": "Risk & Compliance",
        "approval_owner": "Compliance Manager",
        "requestable": True,
        "assigned_user_count": 7,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 11, 1),
        "source_system": "CyberArk PAM",
        "source_type": "pam",
        "external_id": "cyberark-role-readonly-prd-001",
        "sync_status": "synced",
    },

    # ── Azure ─────────────────────────────────────────────────────────────────
    {
        "role_name": "Azure-Global-Administrator",
        "application": "Azure",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Highest privilege role in Microsoft Entra ID. Grants unrestricted access to all Azure AD administrative features including user and group management, application registration, conditional access policies, and tenant-wide configuration. Can assign any role to any user. Compromise of this role constitutes full tenant compromise. Maximum 3 holders, reviewed monthly.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "CTO",
        "requestable": False,
        "assigned_user_count": 2,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "Microsoft Entra ID",
        "source_type": "idp",
        "external_id": "entra-role-globaladmin-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Azure-Subscription-Contributor",
        "application": "Azure",
        "environment": "PRD",
        "access_type": "Contributor",
        "is_privileged": True,
        "description": "Grants full access to create, manage, and delete all Azure resources within the production subscription, excluding role assignments and Azure Policy. Users can deploy infrastructure, modify networking, access storage accounts, and manage compute resources. Cannot grant access to others. Intended for senior cloud engineers managing production infrastructure.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": False,
        "assigned_user_count": 8,
        "stale_finding_count": 4,
        "last_reviewed_date": date(2025, 10, 15),
        "source_system": "Microsoft Entra ID",
        "source_type": "idp",
        "external_id": "entra-role-subcontrib-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Azure-Reader-PRD",
        "application": "Azure",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Provides read-only visibility across all resources in the Azure production subscription. Users can view resource configurations, monitor metrics, and review deployment logs but cannot create, modify, or delete any resources. Suitable for project managers, architects, and audit teams who need visibility without operational access.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": True,
        "assigned_user_count": 22,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 11, 20),
        "source_system": "Microsoft Entra ID",
        "source_type": "idp",
        "external_id": "entra-role-reader-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Azure-Subscription-Contributor-UAT",
        "application": "Azure",
        "environment": "UAT",
        "access_type": "Contributor",
        "is_privileged": False,
        "description": "Contributor access to the Azure UAT subscription for pre-production infrastructure testing and validation. Allows engineers to deploy and test infrastructure changes before promoting to production. Intended for cloud engineers working on UAT validation cycles. Changes in this environment do not affect production workloads.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": True,
        "assigned_user_count": 14,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 5),
        "source_system": "Microsoft Entra ID",
        "source_type": "idp",
        "external_id": "entra-role-subcontrib-uat-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Azure-DevOps-Project-Admin",
        "application": "Azure",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Grants project administrator rights in Azure DevOps including pipeline configuration, repository permissions, branch policies, service connection management, and agent pool administration. Users can modify CI/CD pipelines and control deployment gates. Misuse could result in unauthorised code deployment to production environments.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": False,
        "assigned_user_count": 6,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 9, 30),
        "source_system": "Microsoft Entra ID",
        "source_type": "idp",
        "external_id": "entra-role-devopsadmin-prd-001",
        "sync_status": "synced",
    },

    # ── GitHub ────────────────────────────────────────────────────────────────
    {
        "role_name": "GitHub-Engineering-Maintainer",
        "application": "GitHub",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Provides maintainer-level access to engineering repositories in GitHub Enterprise. Users can push to protected branches, manage pull requests, configure branch protection rules, and manage repository settings. Cannot delete repositories or manage organisation-level settings. Intended for senior engineers and tech leads actively contributing to production codebases.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Engineering Manager",
        "requestable": True,
        "assigned_user_count": 18,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 11, 10),
        "source_system": "GitHub Enterprise",
        "source_type": "scm",
        "external_id": "github-role-maintainer-001",
        "sync_status": "synced",
    },
    {
        "role_name": "GitHub-Org-Owner",
        "application": "GitHub",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Organisation owner access in GitHub Enterprise granting full control over all repositories, teams, members, and organisation settings. Can add or remove members, manage billing, configure SSO, and delete any repository. Extremely high-risk role — organisation owner compromise could result in full codebase exfiltration. Maximum 2 holders.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "CTO",
        "requestable": False,
        "assigned_user_count": 2,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 10, 1),
        "source_system": "GitHub Enterprise",
        "source_type": "scm",
        "external_id": "github-role-orgowner-001",
        "sync_status": "synced",
    },
    {
        "role_name": "GitHub-Read-Only",
        "application": "GitHub",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Read-only access to designated engineering repositories in GitHub Enterprise. Users can clone repositories, view code, and read pull requests and issues but cannot push code or create branches. Suitable for contractors, auditors, and non-engineering staff who need code visibility without commit access.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Engineering Manager",
        "requestable": True,
        "assigned_user_count": 31,
        "stale_finding_count": 5,
        "last_reviewed_date": date(2025, 10, 20),
        "source_system": "GitHub Enterprise",
        "source_type": "scm",
        "external_id": "github-role-readonly-001",
        "sync_status": "synced",
    },

    # ── Jira ──────────────────────────────────────────────────────────────────
    {
        "role_name": "Jira-Project-Administrator",
        "application": "Jira",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": False,
        "description": "Grants project administration rights in Jira Software including workflow configuration, custom field management, permission scheme editing, and notification scheme management within assigned projects. Cannot manage global Jira settings or create new projects. Intended for project leads and scrum masters managing their own project spaces.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": True,
        "assigned_user_count": 11,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 11, 5),
        "source_system": "Atlassian Cloud",
        "source_type": "itsm",
        "external_id": "jira-role-projectadmin-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Jira-Service-Desk-Agent",
        "application": "Jira",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Provides service desk agent access in Jira Service Management. Agents can view and respond to customer requests, manage queues, add internal comments, transition issues, and access the customer portal. Suitable for IT support staff and service delivery teams handling incoming requests and incidents.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "Service Delivery Manager",
        "requestable": True,
        "assigned_user_count": 16,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 3),
        "source_system": "Atlassian Cloud",
        "source_type": "itsm",
        "external_id": "jira-role-sdagent-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Jira-Global-Admin",
        "application": "Jira",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full global administrator access to Jira Software and Jira Service Management. Can create and delete projects, manage global permission schemes, configure issue types, manage users and groups, install add-ons, and access all project data. Reserved for Atlassian platform administrators only.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": False,
        "assigned_user_count": 3,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 8, 1),
        "source_system": "Atlassian Cloud",
        "source_type": "itsm",
        "external_id": "jira-role-globaladmin-001",
        "sync_status": "synced",
    },

    # ── ServiceNow ────────────────────────────────────────────────────────────
    {
        "role_name": "ServiceNow-Change-Manager",
        "application": "ServiceNow",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Provides change management authority in ServiceNow ITSM. Users can create, review, approve, and close change requests, manage the change calendar, and run CAB meetings. Can also access change metrics and reporting. Intended for IT change managers and release coordinators responsible for the change advisory board process.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": True,
        "assigned_user_count": 9,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 11, 25),
        "source_system": "ServiceNow ITSM",
        "source_type": "itsm",
        "external_id": "snow-role-changemgr-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "ServiceNow-Admin",
        "application": "ServiceNow",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full administrative access to ServiceNow platform including application development, workflow configuration, integration management, user provisioning, and system properties. Admin users can impersonate other users, access all records, modify business rules, and deploy updates to production. Restricted to ServiceNow platform team only.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": False,
        "assigned_user_count": 4,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 7, 15),
        "source_system": "ServiceNow ITSM",
        "source_type": "itsm",
        "external_id": "snow-role-admin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "ServiceNow-ITSM-Analyst",
        "application": "ServiceNow",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Standard ITSM analyst access in ServiceNow enabling management of incident, problem, and service request records. Analysts can create, update, assign, and resolve tickets, add work notes, and view the CMDB. Cannot modify workflow logic or system configuration. Suitable for IT operations staff handling day-to-day service management.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "Service Delivery Manager",
        "requestable": True,
        "assigned_user_count": 28,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "ServiceNow ITSM",
        "source_type": "itsm",
        "external_id": "snow-role-itsmanalyst-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "ServiceNow-GRC-Editor",
        "application": "ServiceNow",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Provides editor access to the ServiceNow GRC (Governance, Risk and Compliance) module. Users can create and update risk registers, control frameworks, audit engagements, and compliance tasks. Cannot publish or approve GRC records. Intended for governance analysts and risk officers managing the organisation's GRC programme.",
        "owner_team": "Risk & Compliance",
        "approval_owner": "Compliance Manager",
        "requestable": True,
        "assigned_user_count": 6,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 10, 10),
        "source_system": "ServiceNow ITSM",
        "source_type": "itsm",
        "external_id": "snow-role-grceditor-prd-001",
        "sync_status": "synced",
    },

    # ── Okta ──────────────────────────────────────────────────────────────────
    {
        "role_name": "Okta-App-Administrator",
        "application": "Okta",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Grants application administrator rights in Okta IAM including SSO application configuration, SAML/OIDC setup, group assignment management, and application-level policy configuration. Users can modify which groups have access to which applications. Misuse could result in unauthorised access grants across all Okta-integrated applications. Restricted to IAM engineers.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": False,
        "assigned_user_count": 4,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 9, 15),
        "source_system": "Okta IAM",
        "source_type": "idp",
        "external_id": "okta-role-appadmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Okta-Super-Admin",
        "application": "Okta",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Highest privilege role in Okta granting full control over the entire identity platform including user lifecycle management, group policies, authenticator configuration, API access management, and org-level settings. Super admins can bypass MFA policies, create API tokens, and modify all security configurations. Compromise is equivalent to full identity infrastructure breach.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "CTO",
        "requestable": False,
        "assigned_user_count": 2,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 8, 1),
        "source_system": "Okta IAM",
        "source_type": "idp",
        "external_id": "okta-role-superadmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Okta-Read-Only-Admin",
        "application": "Okta",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Read-only administrative access to Okta including visibility into users, groups, applications, policies, and system logs. Cannot modify any configurations or manage user access. Used by auditors and compliance teams conducting identity governance reviews and access certification campaigns.",
        "owner_team": "Risk & Compliance",
        "approval_owner": "Compliance Manager",
        "requestable": True,
        "assigned_user_count": 5,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 11, 15),
        "source_system": "Okta IAM",
        "source_type": "idp",
        "external_id": "okta-role-readonlyadmin-prd-001",
        "sync_status": "synced",
    },

    # ── AWS ───────────────────────────────────────────────────────────────────
    {
        "role_name": "AWS-Production-ReadOnly",
        "application": "AWS",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Read-only access to AWS production environment via the ReadOnlyAccess managed policy. Provides visibility into EC2 instances, S3 buckets, RDS databases, Lambda functions, CloudWatch metrics, and CloudTrail logs. Cannot create, modify, or delete any AWS resources. Used by architects, auditors, and operations teams monitoring production infrastructure.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": True,
        "assigned_user_count": 19,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 11, 30),
        "source_system": "AWS IAM",
        "source_type": "cloud_iam",
        "external_id": "aws-role-readonly-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "AWS-IAM-Administrator",
        "application": "AWS",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full IAM administrative access in AWS production. Users can create, modify, and delete IAM users, roles, groups, and policies. Can assign any permission to any principal including escalation to AdministratorAccess. This role represents maximum privilege escalation risk in AWS. Requires CTO approval, quarterly review, and must use hardware MFA.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "CTO",
        "requestable": False,
        "assigned_user_count": 3,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 9, 1),
        "source_system": "AWS IAM",
        "source_type": "cloud_iam",
        "external_id": "aws-role-iamadmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "AWS-CloudOps-ReadOnly",
        "application": "AWS",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Scoped read-only access to AWS cloud operations resources including EC2, EKS, CloudWatch, Systems Manager, and Config. Provides the visibility needed by CloudOps engineers monitoring infrastructure health without the ability to make changes. Used by on-call engineers who need to investigate alerts and review resource states.",
        "owner_team": "Infrastructure Operations",
        "approval_owner": "Infrastructure Manager",
        "requestable": True,
        "assigned_user_count": 11,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "AWS IAM",
        "source_type": "cloud_iam",
        "external_id": "aws-role-cloudops-readonly-001",
        "sync_status": "synced",
    },
    {
        "role_name": "AWS-S3-DataLake-ReadOnly",
        "application": "AWS",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Scoped read access to designated S3 data lake buckets in AWS production. Allows data analysts and BI engineers to read raw and processed datasets without access to other AWS services. Bucket policies restrict access to approved prefixes only. Suitable for analysts consuming data from the central data lake for reporting and analytics.",
        "owner_team": "Finance",
        "approval_owner": "Finance Manager",
        "requestable": True,
        "assigned_user_count": 14,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 11, 10),
        "source_system": "AWS IAM",
        "source_type": "cloud_iam",
        "external_id": "aws-role-s3datalake-readonly-001",
        "sync_status": "synced",
    },
    {
        "role_name": "AWS-Developer-UAT",
        "application": "AWS",
        "environment": "UAT",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Developer access to the AWS UAT account allowing creation and management of compute, storage, and application resources for testing purposes. Excludes IAM, networking, and security service modifications. Engineers use this role to deploy and test application changes before production promotion. No access to production data or resources.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": True,
        "assigned_user_count": 22,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 5),
        "source_system": "AWS IAM",
        "source_type": "cloud_iam",
        "external_id": "aws-role-developer-uat-001",
        "sync_status": "synced",
    },

    # ── SailPoint ─────────────────────────────────────────────────────────────
    {
        "role_name": "SailPoint-Identity-Analyst",
        "application": "SailPoint",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Provides identity analyst access in SailPoint IdentityNow including the ability to run access certifications, review entitlements, manage joiner-mover-leaver workflows, and review access request history. Analysts can make provisioning recommendations but require approver sign-off for changes. Intended for IAM governance teams conducting access reviews.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": True,
        "assigned_user_count": 7,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 11, 20),
        "source_system": "SailPoint IdentityNow",
        "source_type": "iga",
        "external_id": "sailpoint-role-idanalyst-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "SailPoint-Admin",
        "application": "SailPoint",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full administrative access to SailPoint IdentityNow including source connector configuration, role modelling, access policy management, workflow design, and system integration settings. Admins control the entire identity governance infrastructure and can override provisioning decisions. Restricted to SailPoint platform administrators and senior IAM engineers.",
        "owner_team": "Enterprise Applications",
        "approval_owner": "IT Manager",
        "requestable": False,
        "assigned_user_count": 3,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 8, 15),
        "source_system": "SailPoint IdentityNow",
        "source_type": "iga",
        "external_id": "sailpoint-role-admin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "SailPoint-Certifier",
        "application": "SailPoint",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Grants access certification authority in SailPoint allowing users to review and certify or revoke access entitlements during scheduled certification campaigns. Certifiers can review their direct reports' or assigned population's access, make certification decisions, and add comments. Typically assigned to managers and business owners during quarterly access reviews.",
        "owner_team": "Risk & Compliance",
        "approval_owner": "Compliance Manager",
        "requestable": True,
        "assigned_user_count": 41,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "SailPoint IdentityNow",
        "source_type": "iga",
        "external_id": "sailpoint-role-certifier-prd-001",
        "sync_status": "synced",
    },

    # ── Cribl ─────────────────────────────────────────────────────────────────
    {
        "role_name": "Cribl-Stream-Operator",
        "application": "Cribl",
        "environment": "PRD",
        "access_type": "Operator",
        "is_privileged": False,
        "description": "Provides operational access to Cribl Stream in production. Operators can monitor pipeline health, view metrics and dashboards, manage worker group deployments, and restart processing pipelines. Cannot modify pipeline logic, routing rules, or source/destination configurations. Used by SOC engineers and platform operators monitoring data pipelines.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 8,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 11, 15),
        "source_system": "Cribl Stream",
        "source_type": "data_pipeline",
        "external_id": "cribl-role-operator-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Cribl-Stream-Admin",
        "application": "Cribl",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full administrative access to Cribl Stream production environment. Admins can create and modify pipelines, configure data sources and destinations, manage routing rules, handle credentials for integrations, and manage user access. Changes can affect the flow of all security telemetry data to SIEM and storage destinations. Restricted to platform administrators.",
        "owner_team": "Cyber Security",
        "approval_owner": "CISO",
        "requestable": False,
        "assigned_user_count": 3,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 10, 1),
        "source_system": "Cribl Stream",
        "source_type": "data_pipeline",
        "external_id": "cribl-role-admin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Cribl-Write-TST",
        "application": "Cribl",
        "environment": "TST",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Write access to Cribl Stream test environment allowing engineers to design and test new pipeline configurations, routing logic, and data transformations. Changes are isolated from production data flows and can be used to validate detection content and pipeline performance before UAT promotion. Used by security engineers building new data ingestion pipelines.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 6,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 3),
        "source_system": "Cribl Stream",
        "source_type": "data_pipeline",
        "external_id": "cribl-role-write-tst-001",
        "sync_status": "synced",
    },

    # ── Additional cross-platform roles ───────────────────────────────────────
    {
        "role_name": "Terraform-Cloud-Operator",
        "application": "Terraform",
        "environment": "PRD",
        "access_type": "Operator",
        "is_privileged": True,
        "description": "Grants operator access to Terraform Cloud workspaces including the ability to trigger runs, approve applies, manage variables, and view state files. Operators can execute infrastructure changes across cloud environments as defined in Terraform configurations. High-risk role — a misconfigured Terraform apply can affect production infrastructure at scale.",
        "owner_team": "Cloud Engineering",
        "approval_owner": "Cloud Engineering Lead",
        "requestable": False,
        "assigned_user_count": 7,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 10, 20),
        "source_system": "Terraform Cloud",
        "source_type": "iac",
        "external_id": "terraform-role-operator-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Sentinel-Incident-Responder",
        "application": "Microsoft Sentinel",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": True,
        "description": "Provides Microsoft Sentinel incident responder access allowing analysts to investigate, triage, and close security incidents. Users can run investigation queries, add comments, assign incidents, run playbooks, and access entity data. Cannot modify analytics rules or data connector settings. Core role for SOC analysts actively responding to security incidents.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 10,
        "stale_finding_count": 3,
        "last_reviewed_date": date(2025, 11, 1),
        "source_system": "Microsoft Sentinel",
        "source_type": "siem",
        "external_id": "sentinel-role-responder-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "CrowdStrike-SOC-Analyst",
        "application": "CrowdStrike",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "SOC analyst access to CrowdStrike Falcon enabling endpoint detection investigation, alert triage, threat hunting, and host containment actions. Analysts can run real-time response sessions, quarantine files, and push prevention policy updates. Intended for SOC analysts conducting endpoint threat investigations and responding to Falcon detections.",
        "owner_team": "Cyber Security",
        "approval_owner": "SOC Lead",
        "requestable": True,
        "assigned_user_count": 9,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 11, 25),
        "source_system": "CrowdStrike Falcon",
        "source_type": "edr",
        "external_id": "crowdstrike-role-socanalyst-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Workday-HR-Administrator",
        "application": "Workday",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full HR administrator access in Workday HCM including employee record management, org structure changes, compensation administration, and HR business process configuration. Admins can hire, terminate, and transfer employees, modify sensitive compensation data, and configure HR workflows. Restricted to senior HR operations staff. Access to all employee personal and financial data.",
        "owner_team": "Human Resources",
        "approval_owner": "HR Manager",
        "requestable": False,
        "assigned_user_count": 4,
        "stale_finding_count": 1,
        "last_reviewed_date": date(2025, 9, 15),
        "source_system": "Workday HCM",
        "source_type": "hris",
        "external_id": "workday-role-hradmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Workday-Employee-ReadOnly",
        "application": "Workday",
        "environment": "PRD",
        "access_type": "Read",
        "is_privileged": False,
        "description": "Read-only access to Workday employee directory and organisational hierarchy. Users can view basic employee profiles, reporting lines, and department structures. Cannot view compensation, payroll, or sensitive HR data. Used by managers and project leads who need to look up colleagues, understand org structure, or identify the right point of contact.",
        "owner_team": "Human Resources",
        "approval_owner": "HR Manager",
        "requestable": True,
        "assigned_user_count": 156,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "Workday HCM",
        "source_type": "hris",
        "external_id": "workday-role-empreadonly-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "SAP-Finance-Editor",
        "application": "SAP",
        "environment": "PRD",
        "access_type": "Write",
        "is_privileged": False,
        "description": "Finance editor access in SAP S/4HANA providing the ability to create, post, and reverse journal entries, manage accounts payable and receivable transactions, run financial reports, and perform month-end close activities. Users can access general ledger, cost centres, and profit centre data. Intended for finance analysts and accountants managing day-to-day financial operations.",
        "owner_team": "Finance",
        "approval_owner": "Finance Manager",
        "requestable": True,
        "assigned_user_count": 17,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 11, 15),
        "source_system": "SAP S/4HANA",
        "source_type": "erp",
        "external_id": "sap-role-financeeditor-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "SAP-Finance-Admin",
        "application": "SAP",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Administrative access to SAP S/4HANA Finance module including system configuration, financial year management, chart of accounts management, and user access control within Finance. Admins can modify tolerance groups, posting periods, and tax configuration. Changes can affect all financial reporting and compliance obligations. Restricted to SAP Finance administrators.",
        "owner_team": "Finance",
        "approval_owner": "CFO",
        "requestable": False,
        "assigned_user_count": 2,
        "stale_finding_count": 0,
        "last_reviewed_date": date(2025, 8, 1),
        "source_system": "SAP S/4HANA",
        "source_type": "erp",
        "external_id": "sap-role-financeadmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "Ansible-Tower-Operator",
        "application": "Ansible",
        "environment": "PRD",
        "access_type": "Operator",
        "is_privileged": True,
        "description": "Operator access to Ansible Tower/AWX in production allowing execution of approved automation playbooks against infrastructure targets. Users can launch job templates, review job output, and manage inventories within their scope. Cannot create or modify playbooks or job templates. Operator actions can affect many systems simultaneously — requires infrastructure team approval.",
        "owner_team": "Infrastructure Operations",
        "approval_owner": "Infrastructure Manager",
        "requestable": False,
        "assigned_user_count": 8,
        "stale_finding_count": 3,
        "last_reviewed_date": date(2025, 10, 15),
        "source_system": "Ansible Tower",
        "source_type": "automation",
        "external_id": "ansible-role-operator-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "VMware-vSphere-Admin",
        "application": "VMware",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Full vSphere administrator access including VM provisioning and deletion, host configuration, vCenter management, storage and network management, and snapshot operations. Can migrate VMs between hosts and manage resource pools. This role provides deep access to virtualisation infrastructure underpinning production workloads. Reserved for infrastructure platform team members.",
        "owner_team": "Infrastructure Operations",
        "approval_owner": "Infrastructure Manager",
        "requestable": False,
        "assigned_user_count": 5,
        "stale_finding_count": 2,
        "last_reviewed_date": date(2025, 9, 1),
        "source_system": "VMware vSphere",
        "source_type": "virtualisation",
        "external_id": "vmware-role-vspadmin-prd-001",
        "sync_status": "synced",
    },
    {
        "role_name": "AD-Domain-Admins",
        "application": "Active Directory",
        "environment": "PRD",
        "access_type": "Admin",
        "is_privileged": True,
        "description": "Domain administrator membership in Active Directory — the highest privilege group in the on-premises identity environment. Domain Admins have unrestricted access to all systems joined to the domain, can create and modify any user or group object, manage Group Policy, and access all domain controllers. Compromise results in complete domain compromise. Maximum 5 holders, reviewed monthly.",
        "owner_team": "Infrastructure Operations",
        "approval_owner": "Infrastructure Manager",
        "requestable": False,
        "assigned_user_count": 4,
        "stale_finding_count": 5,
        "last_reviewed_date": date(2025, 12, 1),
        "source_system": "Active Directory",
        "source_type": "directory",
        "external_id": "ad-group-domainadmins-001",
        "sync_status": "synced",
    },
]


def seed(db):
    created = 0
    for r in ROLES:
        existing = db.execute(
            text("SELECT id FROM role_catalogue WHERE role_name = :name"),
            {"name": r["role_name"]}
        ).first()
        if not existing:
            db.execute(
                text("""
                    INSERT INTO role_catalogue
                    (role_name, application, environment, access_type, is_privileged,
                     description, owner_team, approval_owner, requestable,
                     assigned_user_count, stale_finding_count, last_reviewed_date,
                     source_system, source_type, external_id, sync_status)
                    VALUES
                    (:role_name, :application, :environment, :access_type, :is_privileged,
                     :description, :owner_team, :approval_owner, :requestable,
                     :assigned_user_count, :stale_finding_count, :last_reviewed_date,
                     :source_system, :source_type, :external_id, :sync_status)
                """),
                r
            )
            created += 1
    db.commit()
    print(f"✅ {created} roles seeded into role catalogue ({len(ROLES) - created} already existed).")


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed(db)
    finally:
        db.close()
